name: "Test merge"

on:
  push:
    branches: [ main, testbranch ]

jobs:
  merge:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: merge
      run: |
        $branchTree = @"
        main = testbranch
        testbranch = othertestbranch, #12326-save-exit-ticket-answer
        "@
        function RunBranch {
            param ([string]$source, [string]$branchName, $destinations)
            if ($branchName -ne $null -and $branchName -ne "") {
              $isNotFound = git checkout "origin/$branchName" -t | Select-String "fatal" -Quiet
              if ($isNotFound -eq $true) { Exit }
              $hasConflict = git merge "origin/$source" | Select-String "CONFLICT" -Quiet
              if ($hasConflict -ne $True) { git push } else { Exit }
              $source = $branchName
            }
            $thisName = $destinations.$source
            if ($thisName -ne $null) {
              Do {
                $this, $thisName = $thisName.Split(",")
                RunBranch -source $source -branchName $this.Trim() -destinations $destinations
              } Until ($thisName -eq $null)
            }
        }
        git pull
        $source = "$env:GITHUB_REF_NAME"
        $destinationMap = ConvertFrom-StringData -StringData $branchTree
        RunBranch -source $source -destinations $destinationMap
      shell: powershell
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}