name: "Test merge"

on:
  push:
    branches: [ main, testbranch ]

jobs:
  merge:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: merge
      run: |
        git pull
        $target = "develop"
        $source = "$env.BRANCH_NAME"
        if ($source -eq "main") { $target = "testbranch" }
        if ($source -eq "testbranch") { $target = "main" }
        git checkout "origin/$target" -t
        $hasConflict = git merge "origin/$source" | Select-String "CONFLICT" -Quiet
        if ($hasConflict -ne $True) { git push } else { git merge --abort }
      shell: powershell
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: ${{ env.GITHUB_REF_NAME }}